javascript:var doc = document;
if (window.frames.length > 0) doc = window.main.document;url = document.URL;
var start = url.indexOf("village");
var end = url.indexOf('&', start);
var id;
if (end > 0) id = url.substring(start, end);elseid = url.substring(start);
if (url.indexOf('screen=market') == -1 || url.indexOf('mode=other_offer') == -1) location.search = '?screen=market&mode=other_offer&' + id;
if (document.getElementById('merchant_exchange')){
  var wood = new Number(doc.getElementById('wood').innerHTML);
  var clay = new Number(doc.getElementById('stone').innerHTML);
  var iron = new Number(doc.getElementById('iron').innerHTML);
  max = Math.max(wood, Math.max(clay, iron));
  min = Math.min(wood, Math.min(clay, iron));
  sell = doc.getElementsByName('res_sell')[3];
  buy = doc.getElementsByName('res_buy')[3];
  if (max == wood) buy.value = 'wood';
  if (max == clay) buy.value = 'stone';
  if (max == iron) buy.value = 'iron';
  if (min == wood) sell.value = 'wood';
  if (min == clay) sell.value = 'stone';
  if (min == iron) sell.value = 'iron';
  $(':input[value=Procurar]').click();
}else{var wood = new Number(doc.getElementById('wood').innerHTML);
  var clay = new Number(doc.getElementById('stone').innerHTML);
  var iron = new Number(doc.getElementById('iron').innerHTML);
  max = Math.max(wood, Math.max(clay, iron));
  min = Math.min(wood, Math.min(clay, iron));
  sell = doc.getElementsByName('res_sell')[0];
  buy = doc.getElementsByName('res_buy')[0];
  if (max == wood) buy.value = 'wood';
  if (max == clay) buy.value = 'stone';
  if (max == iron) buy.value = 'iron';
  if (min == wood) sell.value = 'wood';
  if (min == clay) sell.value = 'stone';
  if (min == iron) sell.value = 'iron';
  $(':input[value=Procurar]').click();};